### PR TITLE
fix: Prevent crash, correctly pass report data to notifications

### LINKED ISSUE #1446: The notifications (bell) tab has started crashing
**Describe the bug**
The notifications tab has stopped working. When you select it, the app crashes. 
In the previous version I had installed (2.10.something), I started getting the error
'''Required value 'actionTaken missing at $[3].report'''
and the number increased to 4 and then 5 as more notifications arrived.
Pressing the "Retry" button underneath made no difference.
I updated to 2.11.0 in the hopes it would fix the problem, but now the app just quits when I click on the bell tab.
The notification that might have caused the problem has a custom emoji in it, if that makes any difference.

I have been using the app for over a month now with various versions, and it has never crashed until I started seeing this problem a few days ago.

**To Reproduce**
1. Open Pachli
2. Click on the Bell icon
3. The animated progress line is displayed for a few seconds
4. App quits

**Expected behavior**
App should show the recent notifications

**Screenshots or video**

**Links**

**Versions**
Android 13, Mastodon 4.2.19, Pachli 2.11.0

**Additional context**
None that I can think of.

**Affirmation**
I couldn't see any other open bugs mentioning notifications

### PR DESCRIPTION
**Pull request by austinhuang0131**
Closes #1446. It is ultimately a quick fix, it has been a while since I actively dealt with Android apps, so my code still needs to be properly reviewed

### CODE REVIEW

File: app/src/main/java/app/pachli/adapter/ReportNotificationViewHolder.kt [hunk 1]
```diff
@@ -74,7 +74,7 @@ class ReportNotificationViewHolder(
             binding.root,
             animateEmojis,
         )
-        val reporteeName = report.targetAccount.name.unicodeWrap().emojify(
+        val reporteeName = report.targetAccount.toTimelineAccount().name.unicodeWrap().emojify(
```
Comment (austinhuang0131) [inline app/src/main/java/app/pachli/adapter/ReportNotificationViewHolder.kt:77]: FYI: on Mastodon's web interface it always uses the handle

**Comment by nikclayton** [comment]
That's great, thanks. LGTM, and I'll merge this in a moment.

Of course, the reward for good work is more work, so is there anything else you want to do? There's a laundry list of low-hanging-fruit if you're interested...
