### PR TITLE
fix: Remove progressbar from status timelines

### LINKED ISSUE #75: Loading indicator showing indefinitely on Home TL
**Describe the bug**
A loading indicator was showing indefinitely on the Home TL. This happened after launching the app from a Follow Request push notification.

Pulling to refresh quickly cleared the loading indicator.

**To Reproduce**
I'm not sure this will happen every time, but this is how it happened for me:
1. Receive a Follow Request notification
2. Click on it
3. Accept the request
4. Press the back button until back to the Home TL
5. See a loading indicator that doesn't dismiss/end

**Expected behavior**
The loading indicator should disappear when loading is finished

**Screenshots or video**

https://github.com/pachli/pachli-android/assets/1063155/c971daf3-4cdb-46f5-a8d1-7b33abb39d62

**Versions**
- Pachli: 1.1
- Server: 4.1.8
- Android 13

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

### PR DESCRIPTION
**Pull request by nikclayton**
Previously the middle-of-screen progress spinner and the spinner that appears on a swipe-to-refresh could get out of sync.

Fix this by removing the middle-of-screen progress spinner from relevant fragments, as the swipe-to-refresh spinner shows the user that an operation is in progress, and also clues them in to the fact that a swipe-to-refresh is possible (by using the common UX control).

Fixes #75

### CODE REVIEW

File: app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt [hunk 1]
```diff
@@ -17,6 +17,7 @@
 package app.pachli.components.conversation
 
 import android.os.Bundle
+import android.util.Log
```
Comment (nikclayton) [inline app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt:20]:
```suggestion
```
