### PR TITLE
fix: Remove old account data before creating FK constraints

### LINKED ISSUE #1320: Pachli 2.10.0 keeps stopping
**Describe the bug**

After updating the pachli app via Obtainium app today, the app do not start

**To Reproduce**
1. update to latest pachli version

**Expected behavior**
App starts (worked flawless before the update)

**Screenshots or video**
If applicable, please add screenshots or video to help explain your problem.

Image

**Links**
If a particular post or posts demonstrate the problem please link to them here.
None

**Versions**
Please include the version of Pachli and Android you are using, and the software version your server is using. Find this on the Pachli "About" screen.

Pachli version 2.10.0 (please also see screenshot)
Android 15 GrapheneOS 2025022700
Pachli about screen cannot be accessed, app crashes.
I am on social.tchncs.de (not my server)

**Additional context**

Crash Report Level Error:

```
type: logcat
osVersion: google/raven/raven:15/AP4A.250205.002/2025022700:user/release-keys
flags: dev options enabled
package: app.pachli:27, targetSdk 34
buffers: main,system,crash,events,kernel
level: error

--------- beginning of main
02-28 17:32:43.979  4778  4778 E app.pachli: Not starting debugger since process cannot load the jdwp agent.
02-28 17:32:44.050  4778  4778 E cutils-trace: Error opening trace file: No such file or directory (2)
02-28 17:32:44.142  4778  4778 E app.pachli: Unable to find pattern file or unable to map it for am
--------- beginning of crash
02-28 17:32:44.857  4778  4853 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-4
02-28 17:32:44.857  4778  4853 E AndroidRuntime: Process: app.pachli, PID: 4778
02-28 17:32:44.857  4778  4853 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: Foreign key violation(s) detected in 'ConversationEntity'.
02-28 17:32:44.857  4778  4853 E AndroidRuntime: Number of different violations discovered: 1
02-28 17:32:44.857  4778  4853 E AndroidRuntime: Number of rows in violation: 11
02-28 17:32:44.857  4778  4853 E AndroidRuntime: Violation(s) detected in the following constraint(s):
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	Parent Table = AccountEntity, Foreign Key Constraint Index = 0
02-28 17:32:44.857  4778  4853 E AndroidRuntime:
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at androidx.room.util.DBUtil.c(SourceFile:45)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at app.pachli.core.database.AppDatabase_AutoMigration_10_11_Impl.a(SourceFile:70)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.e(SourceFile:149)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(SourceFile:10)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:422)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.e(SourceFile:57)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.a(SourceFile:24)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.a0(SourceFile:10)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at androidx.room.RoomDatabase.k(SourceFile:5)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at androidx.room.RoomDatabase.b(SourceFile:1)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at androidx.room.RoomDatabase.o(SourceFile:4)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at app.pachli.core.database.dao.AccountDao_Impl$56.call(SourceFile:9)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.s(SourceFile:81)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.g(SourceFile:6)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:114)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1117)
02-28 17:32:44.857  4778  4853 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8d21e01, Dispatchers.Default]
--------- switch to main
02-28 17:32:45.972  4931  4931 E app.pachli: Not starting debugger since process cannot load the jdwp agent.
02-28 17:32:46.088  4931  4931 E cutils-trace: Error opening trace file: No such file or directory (2)
02-28 17:32:46.245  4931  4931 E app.pachli: Unable to find pattern file or unable to map it for am
--------- switch to crash
02-28 17:32:47.015  4931  5002 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
02-28 17:32:47.015  4931  5002 E AndroidRuntime: Process: app.pachli, PID: 4931
02-28 17:32:47.015  4931  5002 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: Foreign key violation(s) detected in 'ConversationEntity'.
02-28 17:32:47.015  4931  5002 E AndroidRuntime: Number of different violations discovered: 1
02-28 17:32:47.015  4931  5002 E AndroidRuntime: Number of rows in violation: 11
02-28 17:32:47.015  4931  5002 E AndroidRuntime: Violation(s) detected in the following constraint(s):
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	Parent Table = AccountEntity, Foreign Key Constraint Index = 0
02-28 17:32:47.015  4931  5002 E AndroidRuntime:
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at androidx.room.util.DBUtil.c(SourceFile:45)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at app.pachli.core.database.AppDatabase_AutoMigration_10_11_Impl.a(SourceFile:70)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.e(SourceFile:149)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(SourceFile:10)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:422)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.e(SourceFile:57)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.a(SourceFile:24)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.a0(SourceFile:10)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at androidx.room.RoomDatabase.k(SourceFile:5)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at androidx.room.RoomDatabase.b(SourceFile:1)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at androidx.room.RoomDatabase.o(SourceFile:4)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at app.pachli.core.database.dao.AccountDao_Impl$60.call(SourceFile:9)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.s(SourceFile:81)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.g(SourceFile:6)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:114)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1117)
02-28 17:32:47.015  4931  5002 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a0de763, Dispatchers.Default]
--------- switch to main
02-28 17:32:48.611  5138  5138 E app.pachli: Not starting debugger since process cannot load the jdwp agent.
02-28 17:32:48.702  5138  5138 E cutils-trace: Error opening trace file: No such file or directory (2)
02-28 17:32:48.843  5138  5138 E app.pachli: Unable to find pattern file or unable to map it for am
--------- switch to crash
02-28 17:32:49.766  5138  5206 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
02-28 17:32:49.766  5138  5206 E AndroidRuntime: Process: app.pachli, PID: 5138
02-28 17:32:49.766  5138  5206 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: Foreign key violation(s) detected in 'ConversationEntity'.
02-28 17:32:49.766  5138  5206 E AndroidRuntime: Number of different violations discovered: 1
02-28 17:32:49.766  5138  5206 E AndroidRuntime: Number of rows in violation: 11
02-28 17:32:49.766  5138  5206 E AndroidRuntime: Violation(s) detected in the following constraint(s):
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	Parent Table = AccountEntity, Foreign Key Constraint Index = 0
02-28 17:32:49.766  5138  5206 E AndroidRuntime:
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at androidx.room.util.DBUtil.c(SourceFile:45)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at app.pachli.core.database.AppDatabase_AutoMigration_10_11_Impl.a(SourceFile:70)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.e(SourceFile:149)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(SourceFile:10)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:422)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.e(SourceFile:57)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.a(SourceFile:24)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.a0(SourceFile:10)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at androidx.room.RoomDatabase.k(SourceFile:5)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at androidx.room.RoomDatabase.b(SourceFile:1)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at androidx.room.RoomDatabase.o(SourceFile:4)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at app.pachli.core.database.dao.AccountDao_Impl$60.call(SourceFile:9)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.s(SourceFile:81)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.g(SourceFile:6)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:114)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1117)
02-28 17:32:49.766  5138  5206 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6c1b27c, Dispatchers.Default]
--------- switch to main
02-28 17:33:44.524  5757  5757 E app.pachli: Not starting debugger since process cannot load the jdwp agent.
02-28 17:33:44.632  5757  5757 E cutils-trace: Error opening trace file: No such file or directory (2)
02-28 17:33:44.753  5757  5757 E app.pachli: Unable to find pattern file or unable to map it for am
--------- switch to crash
02-28 17:33:45.421  5757  5799 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-4
02-28 17:33:45.421  5757  5799 E AndroidRuntime: Process: app.pachli, PID: 5757
02-28 17:33:45.421  5757  5799 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: Foreign key violation(s) detected in 'ConversationEntity'.
02-28 17:33:45.421  5757  5799 E AndroidRuntime: Number of different violations discovered: 1
02-28 17:33:45.421  5757  5799 E AndroidRuntime: Number of rows in violation: 11
02-28 17:33:45.421  5757  5799 E AndroidRuntime: Violation(s) detected in the following constraint(s):
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	Parent Table = AccountEntity, Foreign Key Constraint Index = 0
02-28 17:33:45.421  5757  5799 E AndroidRuntime:
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at androidx.room.util.DBUtil.c(SourceFile:45)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at app.pachli.core.database.AppDatabase_AutoMigration_10_11_Impl.a(SourceFile:70)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.e(SourceFile:149)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(SourceFile:10)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:422)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.e(SourceFile:57)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.a(SourceFile:24)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.a0(SourceFile:10)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at androidx.room.RoomDatabase.k(SourceFile:5)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at androidx.room.RoomDatabase.b(SourceFile:1)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at androidx.room.RoomDatabase.o(SourceFile:4)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at app.pachli.core.database.dao.AccountDao_Impl$60.call(SourceFile:9)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.s(SourceFile:81)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.g(SourceFile:6)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:114)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1117)
02-28 17:33:45.421  5757  5799 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cbb6672, Dispatchers.Default]
--------- switch to main
02-28 17:33:46.365  5808  5808 E app.pachli: Not starting debugger since process cannot load the jdwp agent.
02-28 17:33:46.435  5808  5808 E cutils-trace: Error opening trace file: No such file or directory (2)
02-28 17:33:46.528  5808  5808 E app.pachli: Unable to find pattern file or unable to map it for am
--------- switch to crash
02-28 17:33:47.190  5808  5848 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
02-28 17:33:47.190  5808  5848 E AndroidRuntime: Process: app.pachli, PID: 5808
02-28 17:33:47.190  5808  5848 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: Foreign key violation(s) detected in 'ConversationEntity'.
02-28 17:33:47.190  5808  5848 E AndroidRuntime: Number of different violations discovered: 1
02-28 17:33:47.190  5808  5848 E AndroidRuntime: Number of rows in violation: 11
02-28 17:33:47.190  5808  5848 E AndroidRuntime: Violation(s) detected in the following constraint(s):
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	Parent Table = AccountEntity, Foreign Key Constraint Index = 0
02-28 17:33:47.190  5808  5848 E AndroidRuntime:
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at androidx.room.util.DBUtil.c(SourceFile:45)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at app.pachli.core.database.AppDatabase_AutoMigration_10_11_Impl.a(SourceFile:70)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.e(SourceFile:149)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(SourceFile:10)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:422)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.e(SourceFile:57)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.a(SourceFile:24)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.a0(SourceFile:10)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at androidx.room.RoomDatabase.k(SourceFile:5)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at androidx.room.RoomDatabase.b(SourceFile:1)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at androidx.room.RoomDatabase.o(SourceFile:4)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at app.pachli.core.database.dao.AccountDao_Impl$60.call(SourceFile:9)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.s(SourceFile:81)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.g(SourceFile:6)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:114)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1117)
02-28 17:33:47.190  5808  5848 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f0f80df, Dispatchers.Default]
--------- switch to main
02-28 17:33:48.022  5860  5860 E app.pachli: Not starting debugger since process cannot load the jdwp agent.
02-28 17:33:48.086  5860  5860 E cutils-trace: Error opening trace file: No such file or directory (2)
02-28 17:33:48.176  5860  5860 E app.pachli: Unable to find pattern file or unable to map it for am
--------- switch to crash
02-28 17:33:48.839  5860  5905 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-5
02-28 17:33:48.839  5860  5905 E AndroidRuntime: Process: app.pachli, PID: 5860
02-28 17:33:48.839  5860  5905 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: Foreign key violation(s) detected in 'ConversationEntity'.
02-28 17:33:48.839  5860  5905 E AndroidRuntime: Number of different violations discovered: 1
02-28 17:33:48.839  5860  5905 E AndroidRuntime: Number of rows in violation: 11
02-28 17:33:48.839  5860  5905 E AndroidRuntime: Violation(s) detected in the following constraint(s):
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	Parent Table = AccountEntity, Foreign Key Constraint Index = 0
02-28 17:33:48.839  5860  5905 E AndroidRuntime:
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at androidx.room.util.DBUtil.c(SourceFile:45)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at app.pachli.core.database.AppDatabase_AutoMigration_10_11_Impl.a(SourceFile:70)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.e(SourceFile:149)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(SourceFile:10)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:422)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.e(SourceFile:57)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.a(SourceFile:24)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.a0(SourceFile:10)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at androidx.room.RoomDatabase.c(SourceFile:11)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at app.pachli.core.database.dao.AccountDao_Impl$55.call(SourceFile:7)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.s(SourceFile:81)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.g(SourceFile:6)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:114)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at a.f.run(SourceFile:521)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1117)
02-28 17:33:48.839  5860  5905 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ff49be6, Dispatchers.Default]
--------- switch to main
02-28 17:33:49.632  5910  5910 E app.pachli: Not starting debugger since process cannot load the jdwp agent.
02-28 17:33:49.699  5910  5910 E cutils-trace: Error opening trace file: No such file or directory (2)
02-28 17:33:49.791  5910  5910 E app.pachli: Unable to find pattern file or unable to map it for am
--------- switch to crash
02-28 17:33:50.452  5910  5953 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-4
02-28 17:33:50.452  5910  5953 E AndroidRuntime: Process: app.pachli, PID: 5910
02-28 17:33:50.452  5910  5953 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: Foreign key violation(s) detected in 'ConversationEntity'.
02-28 17:33:50.452  5910  5953 E AndroidRuntime: Number of different violations discovered: 1
02-28 17:33:50.452  5910  5953 E AndroidRuntime: Number of rows in violation: 11
02-28 17:33:50.452  5910  5953 E AndroidRuntime: Violation(s) detected in the following constraint(s):
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	Parent Table = AccountEntity, Foreign Key Constraint Index = 0
02-28 17:33:50.452  5910  5953 E AndroidRuntime:
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at androidx.room.util.DBUtil.c(SourceFile:45)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at app.pachli.core.database.AppDatabase_AutoMigration_10_11_Impl.a(SourceFile:70)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.e(SourceFile:149)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(SourceFile:10)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:422)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.e(SourceFile:57)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.a(SourceFile:24)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.a0(SourceFile:10)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at androidx.room.RoomDatabase.k(SourceFile:5)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at androidx.room.RoomDatabase.b(SourceFile:1)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at androidx.room.RoomDatabase.o(SourceFile:4)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at app.pachli.core.database.dao.AccountDao_Impl$56.call(SourceFile:9)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.s(SourceFile:81)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.g(SourceFile:6)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:114)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1117)
02-28 17:33:50.452  5910  5953 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c2e943, Dispatchers.Default]
--------- switch to main
02-28 17:33:51.547  5960  5960 E app.pachli: Not starting debugger since process cannot load the jdwp agent.
02-28 17:33:51.636  5960  5960 E cutils-trace: Error opening trace file: No such file or directory (2)
02-28 17:33:51.779  5960  5960 E app.pachli: Unable to find pattern file or unable to map it for am
--------- switch to crash
02-28 17:33:52.841  5960  5985 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
02-28 17:33:52.841  5960  5985 E AndroidRuntime: Process: app.pachli, PID: 5960
02-28 17:33:52.841  5960  5985 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: Foreign key violation(s) detected in 'ConversationEntity'.
02-28 17:33:52.841  5960  5985 E AndroidRuntime: Number of different violations discovered: 1
02-28 17:33:52.841  5960  5985 E AndroidRuntime: Number of rows in violation: 11
02-28 17:33:52.841  5960  5985 E AndroidRuntime: Violation(s) detected in the following constraint(s):
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	Parent Table = AccountEntity, Foreign Key Constraint Index = 0
02-28 17:33:52.841  5960  5985 E AndroidRuntime:
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at androidx.room.util.DBUtil.c(SourceFile:45)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at app.pachli.core.database.AppDatabase_AutoMigration_10_11_Impl.a(SourceFile:70)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.e(SourceFile:149)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(SourceFile:10)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:422)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.e(SourceFile:57)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.a(SourceFile:24)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.a0(SourceFile:10)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at androidx.room.RoomDatabase.k(SourceFile:5)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at androidx.room.RoomDatabase.b(SourceFile:1)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at androidx.room.RoomDatabase.o(SourceFile:4)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at app.pachli.core.database.dao.AccountDao_Impl$60.call(SourceFile:9)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.s(SourceFile:81)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.g(SourceFile:6)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:114)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1117)
02-28 17:33:52.841  5960  5985 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fec4a32, Dispatchers.Default]
```

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.
yes

### PR DESCRIPTION
**Pull request by nikclayton**
The 10 -> 11 database migration adds FK constraints with `AccountEntity.id` as the parent.

Because of previous bugs there may be orphaned data in some tables that references accounts that no longer exist in `AccountEntity`. This causes a crash during migration.

This migration was previously automatic. Rewrite it to be manual, by copying the code that was previously generated and inserting explcit `DELETE` statements ahead of the migration to remove the orphaned rows.

Fixes #1320

### CODE REVIEW

File: core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt [hunk 1]
```diff
@@ -317,6 +317,67 @@ val MIGRATE_8_9 = object : Migration(8, 9) {
     }
 }
 
+/**
+ * Clears references to deleted accounts.
+ *
+ * The migration from 10 -> 11 adds FK relationships to the AccountEntity table. Because of
+ * earlier bugs the child tables in those relationships may contain orphoned rows that
```
Comment (nikclayton) [inline core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt:324]:
```suggestion
 * earlier bugs the child tables in those relationships may contain orphaned rows that
```

Comment (rapidocuento) [reply core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt]: > ```suggestion
>  * earlier bugs the child tables in those relationships may contain orphaned rows that
> ```

652203257afd2a244e9a816992022222e69bd86c
